# Generated by Django 5.1.6 on 2025-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_email', models.EmailField(max_length=254)),
                ('referee_name', models.CharField(max_length=255)),
                ('referee_email', models.EmailField(max_length=254)),
                ('course_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
